# Generated by Django 6.0.7 on 2026-07-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleeper', '0002_add_transactions_synckind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncrun',
            name='kind',
            field=models.CharField(choices=[('players', 'Players'), ('league', 'League'), ('trending', 'Trending'), ('transactions', 'Transactions'), ('stats', 'Stats')], db_index=True, max_length=32),
        ),
    ]
