# Generated by Django 6.0.7 on 2026-07-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleeper', '0005_add_metrics_synckind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncrun',
            name='kind',
            field=models.CharField(choices=[('players', 'Players'), ('league', 'League'), ('trending', 'Trending'), ('transactions', 'Transactions'), ('stats', 'Stats'), ('profiles', 'Profiles'), ('metrics', 'Metrics'), ('valuation', 'Valuation')], db_index=True, max_length=32),
        ),
    ]
