# Generated by Django 6.0.7 on 2026-07-25 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0003_add_playerweekstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('draft_round', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('draft_pick', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('draft_team', models.CharField(blank=True, max_length=8)),
                ('pfr_id', models.CharField(blank=True, max_length=16)),
                ('gsis_id', models.CharField(blank=True, max_length=16)),
                ('height_inches', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_lbs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('forty', models.FloatField(blank=True, null=True)),
                ('bench', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vertical', models.FloatField(blank=True, null=True)),
                ('broad_jump', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cone', models.FloatField(blank=True, null=True)),
                ('shuttle', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=32)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='players.player')),
            ],
            options={
                'indexes': [models.Index(fields=['draft_year'], name='enrichment__draft_y_d7c5a7_idx'), models.Index(fields=['draft_round'], name='enrichment__draft_r_492afd_idx'), models.Index(fields=['pfr_id'], name='enrichment__pfr_id_2f7863_idx')],
            },
        ),
    ]
