# Generated by Django 6.0.7 on 2026-07-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeper_id', models.CharField(max_length=16, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('full_name', models.CharField(blank=True, max_length=128)),
                ('search_full_name', models.CharField(blank=True, max_length=128)),
                ('position', models.CharField(blank=True, max_length=8)),
                ('fantasy_positions', models.JSONField(blank=True, default=list)),
                ('team', models.CharField(blank=True, max_length=8)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('active', models.BooleanField(default=False)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('years_exp', models.PositiveIntegerField(blank=True, null=True)),
                ('rookie_year', models.PositiveIntegerField(blank=True, null=True)),
                ('college', models.CharField(blank=True, max_length=128)),
                ('height', models.CharField(blank=True, max_length=16)),
                ('weight', models.CharField(blank=True, max_length=16)),
                ('depth_chart_position', models.CharField(blank=True, max_length=16)),
                ('depth_chart_order', models.PositiveIntegerField(blank=True, null=True)),
                ('injury_status', models.CharField(blank=True, max_length=64)),
                ('injury_body_part', models.CharField(blank=True, max_length=64)),
                ('search_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['position'], name='players_pla_positio_2502c1_idx'), models.Index(fields=['team'], name='players_pla_team_d27726_idx'), models.Index(fields=['active'], name='players_pla_active_7ea9d6_idx'), models.Index(fields=['search_full_name'], name='players_pla_search__6711f5_idx'), models.Index(fields=['position', 'team'], name='players_pla_positio_11ce15_idx')],
            },
        ),
    ]
