# Generated by Django 6.0.7 on 2026-07-25 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('add', 'Add'), ('drop', 'Drop')], max_length=8)),
                ('count', models.PositiveIntegerField(default=0)),
                ('lookback_hours', models.PositiveIntegerField(default=24)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending', to='players.player')),
            ],
            options={
                'ordering': ['-count'],
                'indexes': [models.Index(fields=['kind', '-count'], name='players_tre_kind_d8d436_idx')],
                'unique_together': {('player', 'kind')},
            },
        ),
    ]
