# Generated by Django 6.0.7 on 2026-07-25 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_trendingplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerWeekStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.PositiveSmallIntegerField()),
                ('week', models.PositiveSmallIntegerField()),
                ('season_type', models.CharField(default='regular', max_length=8)),
                ('kind', models.CharField(choices=[('stat', 'Stat'), ('projection', 'Projection')], max_length=12)),
                ('pts_ppr', models.FloatField(blank=True, null=True)),
                ('pts_half_ppr', models.FloatField(blank=True, null=True)),
                ('pts_std', models.FloatField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_stats', to='players.player')),
            ],
            options={
                'ordering': ['-season', '-week', 'kind'],
                'indexes': [models.Index(fields=['season', 'week', 'kind'], name='players_pla_season_3d99b7_idx'), models.Index(fields=['player', 'kind'], name='players_pla_player__44e1d6_idx'), models.Index(fields=['kind', 'season', 'week'], name='players_pla_kind_bc7607_idx')],
                'unique_together': {('player', 'season', 'week', 'season_type', 'kind')},
            },
        ),
    ]
