# Generated by Django 6.0.7 on 2026-07-25 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_add_playerweekstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSeasonMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.PositiveSmallIntegerField()),
                ('season_type', models.CharField(default='regular', max_length=8)),
                ('position', models.CharField(blank=True, max_length=8)),
                ('games_played', models.PositiveSmallIntegerField(default=0)),
                ('total_ppr', models.FloatField(blank=True, null=True)),
                ('total_half_ppr', models.FloatField(blank=True, null=True)),
                ('total_std', models.FloatField(blank=True, null=True)),
                ('ppg_ppr', models.FloatField(blank=True, null=True)),
                ('ppg_half_ppr', models.FloatField(blank=True, null=True)),
                ('ppg_std', models.FloatField(blank=True, null=True)),
                ('stdev_ppr', models.FloatField(blank=True, null=True)),
                ('floor_ppr', models.FloatField(blank=True, null=True)),
                ('ceiling_ppr', models.FloatField(blank=True, null=True)),
                ('recent_ppg_ppr', models.FloatField(blank=True, null=True)),
                ('form_delta_ppr', models.FloatField(blank=True, null=True)),
                ('targets', models.PositiveIntegerField(blank=True, null=True)),
                ('carries', models.PositiveIntegerField(blank=True, null=True)),
                ('snaps', models.PositiveIntegerField(blank=True, null=True)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_metrics', to='players.player')),
            ],
            options={
                'ordering': ['-season', '-ppg_ppr'],
                'indexes': [models.Index(fields=['season', 'position'], name='players_pla_season_e18444_idx'), models.Index(fields=['player', 'season'], name='players_pla_player__4cc301_idx'), models.Index(fields=['season', '-ppg_ppr'], name='players_pla_season_f48445_idx')],
                'unique_together': {('player', 'season', 'season_type')},
            },
        ),
    ]
