# Generated by Django 6.0.7 on 2026-07-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_add_playerseasonmetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.PositiveSmallIntegerField()),
                ('model_version', models.CharField(default='baseline-v1', max_length=32)),
                ('position', models.CharField(blank=True, max_length=8)),
                ('now_score', models.FloatField(default=0.0)),
                ('prospect_score', models.FloatField(default=0.0)),
                ('horizon_score', models.FloatField(default=0.0)),
                ('horizon_seasons', models.FloatField(default=0.0)),
                ('expires_season', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('tier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('overall_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('components', models.JSONField(blank=True, default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='players.player')),
            ],
            options={
                'ordering': ['-season', 'model_version', '-value'],
                'indexes': [models.Index(fields=['season', 'model_version', '-value'], name='players_pla_season_bb85a1_idx'), models.Index(fields=['season', 'model_version', 'position', '-value'], name='players_pla_season_3ab5a9_idx'), models.Index(fields=['player', 'model_version'], name='players_pla_player__32e400_idx')],
                'unique_together': {('player', 'season', 'model_version')},
            },
        ),
    ]
