# Generated by Django 6.0.7 on 2026-07-25 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sleeper_user_id', models.CharField(max_length=32, unique=True)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=64)),
                ('avatar', models.CharField(blank=True, max_length=64)),
                ('is_me', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='SleeperAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=64)),
                ('sleeper_user_id', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=64)),
                ('avatar', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.CharField(max_length=8)),
                ('sleeper_league_id', models.CharField(max_length=32, unique=True)),
                ('previous_sleeper_league_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('total_rosters', models.PositiveIntegerField(default=0)),
                ('roster_positions', models.JSONField(blank=True, default=list)),
                ('scoring_settings', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='leagues.league')),
            ],
            options={
                'ordering': ['-season'],
                'unique_together': {('league', 'season')},
            },
        ),
        migrations.CreateModel(
            name='RosterSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.CharField(choices=[('starter', 'Starter'), ('bench', 'Bench'), ('taxi', 'Taxi'), ('ir', 'IR')], default='bench', max_length=16)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_slots', to='players.player')),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roster_id', models.PositiveIntegerField()),
                ('team_name', models.CharField(blank=True, max_length=128)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('ties', models.PositiveIntegerField(default=0)),
                ('points_for', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('points_against', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('waiver_budget_used', models.PositiveIntegerField(default=0)),
                ('league_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='leagues.leagueseason')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='leagues.manager')),
                ('players', models.ManyToManyField(related_name='teams', through='leagues.RosterSlot', to='players.player')),
            ],
            options={
                'ordering': ['-wins', '-points_for'],
                'unique_together': {('league_season', 'roster_id')},
            },
        ),
        migrations.AddField(
            model_name='rosterslot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_slots', to='leagues.team'),
        ),
        migrations.AddIndex(
            model_name='rosterslot',
            index=models.Index(fields=['team', 'slot'], name='leagues_ros_team_id_df10a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rosterslot',
            unique_together={('team', 'player')},
        ),
    ]
