# Generated by Django 6.0.7 on 2026-07-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rosterslot',
            options={'ordering': ['slot', 'lineup_order']},
        ),
        migrations.AddField(
            model_name='rosterslot',
            name='lineup_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rosterslot',
            name='lineup_position',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
