# Generated by Django 6.0.7 on 2026-07-25 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_alter_rosterslot_options_rosterslot_lineup_order_and_more'),
        ('players', '0002_trendingplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sleeper_transaction_id', models.CharField(max_length=32, unique=True)),
                ('week', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, max_length=16)),
                ('status_updated', models.DateTimeField(blank=True, null=True)),
                ('league_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='leagues.leagueseason')),
            ],
            options={
                'ordering': ['-status_updated'],
            },
        ),
        migrations.CreateModel(
            name='TradeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('player', 'Player'), ('pick', 'Pick'), ('faab', 'FAAB')], max_length=8)),
                ('pick_season', models.CharField(blank=True, max_length=8)),
                ('pick_round', models.PositiveIntegerField(blank=True, null=True)),
                ('faab_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('from_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_sent', to='leagues.team')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trade_assets', to='players.player')),
                ('to_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_received', to='leagues.team')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='leagues.trade')),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='TradedPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.CharField(max_length=8)),
                ('round', models.PositiveIntegerField()),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks_owned', to='leagues.manager')),
                ('league_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traded_picks', to='leagues.leagueseason')),
                ('original_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks_originally_owned', to='leagues.manager')),
            ],
            options={
                'ordering': ['season', 'round'],
            },
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['league_season', '-status_updated'], name='leagues_tra_league__7865ab_idx'),
        ),
        migrations.AddIndex(
            model_name='tradedpick',
            index=models.Index(fields=['league_season', 'season'], name='leagues_tra_league__0a47a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tradedpick',
            unique_together={('league_season', 'season', 'round', 'original_owner')},
        ),
    ]
