# Generated by Django 6.0.7 on 2026-07-25 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_trendingplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouting_notes', to='players.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stance', models.CharField(choices=[('acquire', 'Acquire'), ('avoid', 'Avoid')], max_length=8)),
                ('tier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='players.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
